// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYLQwb8UTl2jTugpK_c4LeKpGz-eL5oRU',
    appId: '1:639998482105:web:3b4b84930130bd5083ad68',
    messagingSenderId: '639998482105',
    projectId: 'study-app-2acfe',
    authDomain: 'study-app-2acfe.firebaseapp.com',
    storageBucket: 'study-app-2acfe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6KT7SUQRbRQTFUtx1CdwHPcmbdRX4wr8',
    appId: '1:639998482105:android:aad2c76e7e71509483ad68',
    messagingSenderId: '639998482105',
    projectId: 'study-app-2acfe',
    storageBucket: 'study-app-2acfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHh33zemXwvi01tpy2-bkurEbiQpAYbB8',
    appId: '1:639998482105:ios:0e3bfb2bf148afb483ad68',
    messagingSenderId: '639998482105',
    projectId: 'study-app-2acfe',
    storageBucket: 'study-app-2acfe.appspot.com',
    iosClientId: '639998482105-s0vvrcuuastvomdkr9vliop38vt3pvo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHh33zemXwvi01tpy2-bkurEbiQpAYbB8',
    appId: '1:639998482105:ios:0e3bfb2bf148afb483ad68',
    messagingSenderId: '639998482105',
    projectId: 'study-app-2acfe',
    storageBucket: 'study-app-2acfe.appspot.com',
    iosClientId: '639998482105-s0vvrcuuastvomdkr9vliop38vt3pvo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
